version: '3'
services:
    db:
        image: postgres:12.4-alpine
        ports:
            - "5432:5432"
        environment:
            - "POSTGRES_PASSWORD=password"

    backend:
        build: ./backend/
        image: 3-tier-counter-backend:latest
        ports:
            - "3000:3000"
        environment: 
            - "DB_HOST=db"
        depends_on:
            - db
 
    frontend:
        build: ./frontend/
        image: 3-tier-counter-frontend:latest
        ports:
            - "80:80"
        environment: 
            - "API_ENDPOINT=localhost:3000"